using System.IO;
using UnityEditor;
using UnityEngine;
using HorrorUtez.Rendering;

namespace HorrorUtez.World.Editor
{
    /// <summary>
    /// Turns the vendored prop FBXs under Assets/ThirdParty/Props into PSX-shaded prefabs
    /// that the scene passes can instantiate.
    ///
    /// The meshes ship without usable materials: <see cref="Rendering.Editor.PsxPropImporter"/>
    /// deliberately imports none, because the PSX master graphs take albedo from MainTex
    /// only and a URP/Lit material generated by the FBX importer would just have to be
    /// deleted again. So the materials are authored here, against the original texture where
    /// the pack shipped one and against a generated flat texture where it did not.
    ///
    /// Re-runnable: existing materials and prefabs are overwritten in place, so instances
    /// already in the scene keep their references.
    /// </summary>
    public static class UtezPropAssets
    {
        private const string PropRoot = "Assets/ThirdParty/Props";
        private const string MaterialFolder = "Assets/_Project/Art/Materials/Props";
        private const string TextureFolder = "Assets/_Project/Art/Textures/Props";
        private const string PrefabFolder = "Assets/_Project/Prefabs/Props";

        public const string BenchPrefab = PrefabFolder + "/Bench_Waiting3.prefab";
        public const string ExtinguisherPrefab = PrefabFolder + "/FireExtinguisher.prefab";

        private enum Body { Box, Capsule }

        /// <summary>One material slot on a prop, in the submesh order the FBX exports.</summary>
        private readonly struct Slot
        {
            /// <summary>Material asset name. Also the generated texture name, when there is one.</summary>
            public readonly string Name;
            /// <summary>Original texture from the pack, or null to generate a flat one.</summary>
            public readonly string TexturePath;
            /// <summary>Colour of the generated texture. Ignored when TexturePath is set.</summary>
            public readonly Color Flat;
            /// <summary>Specular highlight, for the chromed metal parts.</summary>
            public readonly bool Specular;

            public Slot(string name, string texturePath, Color flat, bool specular = false)
            {
                Name = name;
                TexturePath = texturePath;
                Flat = flat;
                Specular = specular;
            }
        }

        private readonly struct Def
        {
            public readonly string Name;
            public readonly string FbxPath;
            /// <summary>Indexed by submesh. Order is fixed by the Blender export; see the folder README.</summary>
            public readonly Slot[] Slots;
            public readonly Body Collider;

            public Def(string name, string fbxPath, Slot[] slots, Body collider)
            {
                Name = name;
                FbxPath = fbxPath;
                Slots = slots;
                Collider = collider;
            }
        }

        private static readonly Def[] Defs =
        {
            new("Bench_Waiting3", $"{PropRoot}/Bench_Waiting3/Bench_Waiting3.fbx",
                new[]
                {
                    // Submesh 0: perforated sheet seat and backrest, on the pack's own map.
                    new Slot("Prop_BenchSeat", $"{PropRoot}/Bench_Waiting3/Bench_Seat_Perforated.jpg",
                        default),
                    // Submesh 1: the chromed frame and armrests. The pack's chrome was a
                    // raytraced material with no texture at all, so this is generated.
                    new Slot("Prop_Chrome", null, new Color(0.66f, 0.68f, 0.70f), specular: true),
                },
                Body.Box),

            new("FireExtinguisher", $"{PropRoot}/FireExtinguisher/FireExtinguisher.fbx",
                new[]
                {
                    new Slot("Prop_FireExtinguisher",
                        $"{PropRoot}/FireExtinguisher/FireExtinguisher_Diffuse.jpg", default),
                },
                Body.Capsule),
        };

        [MenuItem("HORROR-UTEZ/Rebuild PSX Prop Assets")]
        public static void EnsureAll()
        {
            Directory.CreateDirectory(MaterialFolder);
            Directory.CreateDirectory(TextureFolder);
            Directory.CreateDirectory(PrefabFolder);

            var shader = Shader.Find(PsxShaderProperties.UnlitMaster);
            if (shader == null)
            {
                Debug.LogError($"[PROPS] Shader not found: {PsxShaderProperties.UnlitMaster}. " +
                               "Is Assets/ThirdParty/URP-PSX vendored?");
                return;
            }

            int built = 0;
            foreach (var def in Defs)
            {
                if (BuildPrefab(def, shader))
                    built++;
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"[PROPS] {built}/{Defs.Length} prop prefabs written to {PrefabFolder}");
        }

        private static bool BuildPrefab(Def def, Shader shader)
        {
            var source = AssetDatabase.LoadAssetAtPath<GameObject>(def.FbxPath);
            if (source == null)
            {
                Debug.LogError($"[PROPS] Missing model {def.FbxPath}");
                return false;
            }

            var materials = new Material[def.Slots.Length];
            for (int i = 0; i < def.Slots.Length; i++)
                materials[i] = WriteMaterial(def.Slots[i], shader);

            var instance = (GameObject)PrefabUtility.InstantiatePrefab(source);
            try
            {
                instance.name = def.Name;

                var filter = instance.GetComponentInChildren<MeshFilter>();
                var renderer = instance.GetComponentInChildren<MeshRenderer>();
                if (filter == null || renderer == null || filter.sharedMesh == null)
                {
                    Debug.LogError($"[PROPS] {def.Name} has no mesh renderer.");
                    return false;
                }

                var mesh = filter.sharedMesh;
                if (mesh.subMeshCount != def.Slots.Length)
                {
                    // Not fatal — Unity pads or drops the tail — but it means the FBX was
                    // re-exported with different slots and the Def is now describing the
                    // wrong surfaces, which is invisible until someone looks at it in game.
                    Debug.LogWarning($"[PROPS] {def.Name}: FBX has {mesh.subMeshCount} submeshes " +
                                     $"but {def.Slots.Length} materials are defined. Materials will " +
                                     "be assigned in order and may not land on the intended surface.");
                }
                renderer.sharedMaterials = materials;

                AddCollider(instance, def.Collider, mesh.bounds);

                // Props never move, so let them batch and occlude like the buildings do.
                foreach (var child in instance.GetComponentsInChildren<MeshRenderer>())
                    GameObjectUtility.SetStaticEditorFlags(child.gameObject,
                        StaticEditorFlags.BatchingStatic | StaticEditorFlags.OccluderStatic |
                        StaticEditorFlags.OccludeeStatic);

                string path = $"{PrefabFolder}/{def.Name}.prefab";
                PrefabUtility.SaveAsPrefabAsset(instance, path);
                // Vertex count, not triangles: the importer marks these meshes non-readable,
                // so mesh.triangles is off limits even in the editor.
                Debug.Log($"[PROPS] {def.Name}: {mesh.vertexCount} verts, " +
                          $"{mesh.subMeshCount} submeshes, bounds {mesh.bounds.size} -> {path}");
                return true;
            }
            finally
            {
                Object.DestroyImmediate(instance);
            }
        }

        /// <summary>
        /// A primitive collider, sized off the mesh bounds. A MeshCollider on a decimated
        /// prop costs far more than the shape is worth, and the player only ever bumps into
        /// these — nothing needs to shoot through the gap under a bench.
        /// </summary>
        private static void AddCollider(GameObject instance, Body body, Bounds bounds)
        {
            switch (body)
            {
                case Body.Capsule:
                    var capsule = instance.AddComponent<CapsuleCollider>();
                    capsule.direction = 1; // Y
                    capsule.center = bounds.center;
                    capsule.height = bounds.size.y;
                    capsule.radius = Mathf.Min(bounds.extents.x, bounds.extents.z);
                    break;

                default:
                    var box = instance.AddComponent<BoxCollider>();
                    box.center = bounds.center;
                    box.size = bounds.size;
                    break;
            }
        }

        private static Material WriteMaterial(Slot slot, Shader shader)
        {
            var texture = slot.TexturePath != null
                ? AssetDatabase.LoadAssetAtPath<Texture2D>(slot.TexturePath)
                : EnsureFlatTexture(slot);

            if (texture == null)
                Debug.LogWarning($"[PROPS] Missing texture for {slot.Name} at {slot.TexturePath}");

            string path = $"{MaterialFolder}/{slot.Name}.mat";
            var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (mat == null)
            {
                mat = new Material(shader);
                AssetDatabase.CreateAsset(mat, path);
            }
            mat.shader = shader;

            mat.SetTexture(PsxShaderProperties.MainTex, texture);
            mat.SetVector(PsxShaderProperties.Tiling, Vector2.one);
            mat.SetFloat(PsxShaderProperties.IsLit, 1f);
            mat.SetFloat(PsxShaderProperties.IsSpecular, slot.Specular ? 1f : 0f);
            mat.SetFloat(PsxShaderProperties.Smoothness, slot.Specular ? 0.55f : 0f);
            if (slot.Specular)
                mat.SetColor(PsxShaderProperties.Specular, new Color(0.85f, 0.87f, 0.90f));

            // Props are small and often close to the camera, where jitter reads as a broken
            // mesh rather than a PS1 one. High vertex resolution keeps the snapping present
            // but subtle, matching what the terrain materials do.
            mat.SetFloat(PsxShaderProperties.UseVertexJitter, 1f);
            mat.SetFloat(PsxShaderProperties.VertexResolution, 560f);

            // Affine warping is off here on purpose. The style guide reserves it for floors
            // and large walls; on a prop the size of an extinguisher the polygons are too
            // small for the swim to read as anything but a texture glitch.
            mat.SetFloat(PsxShaderProperties.UseAffine, 0f);

            // Same texel budget as the terrain, so props do not look sharper than the world
            // they stand on.
            mat.SetFloat(PsxShaderProperties.UsePixelation, 1f);
            mat.SetFloat(PsxShaderProperties.TextureResolution, 256f);

            mat.SetFloat(PsxShaderProperties.UseColorPrecision, 1f);
            mat.SetFloat(PsxShaderProperties.ColorPrecision, 6f);

            mat.SetFloat(PsxShaderProperties.UseCameraClipping, 0f);

            EditorUtility.SetDirty(mat);
            return mat;
        }

        /// <summary>
        /// A small flat texture for slots whose pack shipped none. The PSX graphs expose no
        /// base colour, so even a plain surface needs something in MainTex.
        /// </summary>
        private static Texture2D EnsureFlatTexture(Slot slot)
        {
            const int size = 32;
            string path = $"{TextureFolder}/{slot.Name}.asset";

            var pixels = new Color32[size * size];
            var rng = new System.Random(slot.Name.GetHashCode());
            for (int i = 0; i < pixels.Length; i++)
            {
                // A touch of per-texel noise, otherwise the colour precision pass turns a
                // flat fill into one dead uniform block.
                float n = 1f + ((float)rng.NextDouble() - 0.5f) * 0.06f;
                pixels[i] = new Color(slot.Flat.r * n, slot.Flat.g * n, slot.Flat.b * n, 1f);
            }

            var tex = new Texture2D(size, size, TextureFormat.RGBA32, mipChain: false)
            {
                filterMode = FilterMode.Point,
                wrapMode = TextureWrapMode.Repeat,
                anisoLevel = 0,
            };
            tex.SetPixels32(pixels);
            tex.Apply();

            var existing = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
            if (existing == null)
            {
                AssetDatabase.CreateAsset(tex, path);
                return AssetDatabase.LoadAssetAtPath<Texture2D>(path);
            }

            EditorUtility.CopySerialized(tex, existing);
            Object.DestroyImmediate(tex);
            return existing;
        }
    }
}
